definitions:
  block:
    description: block defines data format for blockchain
    properties:
      CurrentHash:
        type: string
      Nonce:
        format: int32
        type: integer
      PrevHash:
        description: Hash of previous block
        type: string
      Timestamp:
        type: string
    required:
    - PrevHash
    type: object
    x-go-package: github.com/emrahsariboz/blockchain-restapi/web/blockchain
paths:
  /:
    get:
      description: |-
        returns list of blocks
        responses
        200: blockResponse
      operationId: getTag
  /add:
    put:
      consumes:
      - application/json
      description: |-
        responses
        200 nocontent
      operationId: NewBlock
      produces:
      - application/json
responses:
  blockResponse:
    description: List of blocks returns in the response
    schema:
      items:
        $ref: '#/definitions/block'
      type: array
  noContent:
    description: ""
swagger: "2.0"
